### ISSUE TITLE
0.4.5 fails with perccli

### ISSUE THREAD

**Issue by avk999** [trunet/puppet-storcli#17]
if perccli is used (vendor is Dell and perccli64 exists) facter/megaraid.rb tries to call it with `nolog` which perccli doesn't support, so facter fails.

**Comment by avk999** [comment]
perccli:

```
Storage Command Line Tool  Ver 007.0318.0000.0000 Jan 03, 2018
```

**Comment by jcpunk** [comment]
I'll take a look at this.

**Comment by jcpunk** [comment]
Can you test the linked pull request and verify it is working as you'd expect?

**Comment by jcpunk** [comment]
Hmmm, I'm showing the current version is : `PercCli SAS Customization Utility Ver 007.2313.0000.0000 Mar 07, 2023`

from: https://www.dell.com/support/home/en-lt/drivers/driversdetails?driverid=tdghn

And it shows a `nolog` option is accepted...

**Comment by jcpunk** [comment]
I've published 1.0.0 with greater clarification on the minimum required versions of `storcli` and `perccli`.

**Comment by avk999** [comment]
Thank you! Right now we are not using this module, I'll get back when we'll be re-enabling it.

**Comment by avk999** [comment]
(closing)
