### ISSUE TITLE
Puppet 7 support

### ISSUE THREAD

**Issue by jcpunk** [trunet/puppet-storcli#4]
Can this module be updated for puppet7?

**Comment by trunet** [comment]
I don't have any servers with storcli anymore. Therefore, PRs are welcome.

**Comment by jcpunk** [comment]
I'll get some PRs up.

While I'm at it, I'll probably work on an extension to set some controller elements.

I've got PRs up to get 99% of the way to puppet7.

**Comment by jcpunk** [comment]
I'll get some PRs up.

While I'm at it, I'll probably work on an extension to set some controller elements.

I've got PRs up to get 99% of the way to puppet7.

**Comment by trunet** [comment]
I added you as a maintainer... Feel free to do whatever you want with it as I'm not using this anymore it's difficult to review, test and approve PRs.

**Comment by jcpunk** [comment]
I've gotten the `production` branch into the state I'd like.

Can you get a new release put up on the forge?

**Comment by trunet** [comment]
If you tag like v0.3.0, it should build and release automatically using https://github.com/trunet/puppet-storcli/blob/production/.github/workflows/main.yaml
